---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  ports:
  - port: 3306
  type: ExternalName
  externalName: 10.0.2.2
---
apiVersion: v1
kind: Service
metadata:
  name: example-app
  labels:
    app: example-app
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
  - port: 3000
    targetPort: 3000
  selector:
    app: example-app
